### ISSUE TITLE
Add bookings#create example edge case tests 

### ISSUE THREAD

**Issue by goozzik** [distribusion/bosi-app-boilerplate#24]
- passenger names with numbers, .e.g `R2D2`
- passenger names with non-standard chars, .e.g `Gènoveva`

**Comment by daniel-whitfield-distribusion** [comment]
passenger named with hyphens e.g. `Mary-lou`
passenger names with spaces e.g. `Bobby Lee`
city names with punctuation e.g. `Saint-Louis-du-Ha! Ha!`, `Westward Ho!`, `Jot ‘Em Down`

**Comment by daniel-whitfield-distribusion** [comment]
city names with urls e.g. `half.com, Oregon`

**Comment by daniel-whitfield-distribusion** [comment]
passengers with very long names e.g. `Hubert Blaine Wolfe­schlegel­stein­hausen­berger­dorff Sr.`

**Comment by goozzik** [comment]
Moved to 

https://youtrack.distribusion.com/youtrack/issue/FBOSI-5?project=FBOSI
